#!/bin/bash

# this needs to go, tied to cygwin and ore-oracle takeover

type -p VBoxManage.exe > /dev/null
case $? in
0)   : ;;
1)   export PATH=/cygdrive/c/Program Files/Sun/xVM VirtualBox:${PATH} ;;
esac
